export const pixelParcelAbi = [
  {
    type: "function",
    name: "userPacks",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "userSeals",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "userSends",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalPacks",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalSeals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalSends",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "packBox",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "sealLabel",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "sendParcel",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "event",
    name: "BoxPacked",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userPacks", type: "uint256", indexed: false },
      { name: "totalPacks", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LabelSealed",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userSeals", type: "uint256", indexed: false },
      { name: "totalSeals", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ParcelSent",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userSends", type: "uint256", indexed: false },
      { name: "totalSends", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;
